# Generated by Django 4.0.6 on 2022-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('preference1', models.CharField(max_length=150)),
                ('preference2', models.CharField(max_length=150)),
                ('preference3', models.CharField(max_length=150)),
            ],
        ),
    ]
