# Generated by Django 4.0.6 on 2022-08-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('university', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('LoB', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('interest1', models.CharField(max_length=150)),
                ('interest2', models.CharField(max_length=150)),
                ('interest3', models.CharField(max_length=150)),
                ('programming1', models.CharField(max_length=150)),
                ('programming2', models.CharField(max_length=150)),
            ],
        ),
    ]
